ResPretrain:
  Train:
    batch_size: 30
    epochs: 4
    lr: 0.0001
    is_load: False
    load_path: "C:/Users/25705/Downloads/documents/fdu/1.6/AI/PJ/1/p3/model_store/Res18_MNIST_load.pth"
    save_path: "C:/Users/25705/Downloads/documents/fdu/1.6/AI/PJ/1/p3/model_store/Res18_MNIST_01.pth"

  Val:  

  General:
    class_num: 10